### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by denisx** [rogozhin/rutypo#1]
Исходная:

'Публикации Наталии Орловой\nНа развилке: каковы шансы, что Банк России снизит ключевую ставку. Протесты дальнобойщиков, волатильный курс рубля и быстрый рост зарплат могут убедить ЦБ не снижать ставку на заседании в пятницу, 28 июля\n<a href="https://alfabank.ru/about/research/orlova/2017/7/28/40080.html?from=AlfaBlankBot">Читать на сайте целиком 📄</a>'

После typo

'Публикации Наталии Орловой\nНа развилке: каковы шансы, что Банк России снизит ключевую ставку. Протесты дальнобойщиков, волатильный курс рубля и быстрый рост зарплат могут убедить ЦБ не снижать ставку на заседании в пятницу, 28 июля\n<a href=“https://alfabank.ru/about/research/orlova/2017/7/28/40080.html?from=AlfaBlankBot”>Читать на сайте целиком 📄</a>'

баг - в ссылке делает ёлочки

**Comment by rogozhin** [comment]
Проект предназначен для типографирования текста. Если ты хочешь работать с хтмлом, напиши обертку, что-то типа
```js 
function typoHtml() {
	const tagList = []
	const textToType = text.replace(/<.+?>/mg, (tag) => {
		tagList.push(tag)
		return '#tag-holder#'
	})

	return rutypo(textToType)
		.replace(/#tag-holder#/im, () => tagList.shift())
}
```

**Comment by denisx** [comment]
Только не `tag-holder`, а `tagHolder`.

**Comment by denisx** [comment]
И не `im` а `gm`. Поправишь?
